trigger:
  - main

variables:
  system.debug: 'true'

stages:
- stage: build
  displayName: Build 
  jobs:
  - job: build
    displayName: Build 
    pool:
      name: local
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - bash: |
        ls -l
        pwd
        echo "$(System.DefaultWorkingDirectory)"
        echo "$(System.ArtifactsDirectory)"
      displayName: Debug Info

    - script: npm install -g bun
      displayName: 'Install Bun'

    - script: |
        bun install
        bunx --bun vite build # Build without verify with TypeScript
      displayName: 'Install Dependencies and Build Project'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false

    - task: PublishPipelineArtifact@0
      inputs:
        targetPath: '$(System.ArtifactsDirectory)'
