# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  name: local

steps:
- task: NodeTool@0
  inputs:
    #versionSpec: '10.x'
    checkLatest: true
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: setup bun
  inputs:
    command: 'custom'
    customCommand: 'install -g bun'
    verbose: true

- bash: bun install
  displayName: 'Bun install'

- bash: bun run build
  displayName: 'Bun build'