trigger:
  - main

pool:
  name: local

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- bash: ls -l

- script: npm install -g bun
  displayName: 'Install Bun'

- script: bun install
  displayName: 'Bun Install'

- script: bun run dev