trigger:
  - main

pool:
  name: local

variables:
  system.debug: 'true'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- bash: |
    ls -l
    pwd

- script: npm install -g bun
  displayName: 'Install Bun'

- script: bun install
  displayName: 'Bun Install'

- script: bunx --bun vite build # Build without verify with TypeScript
  displayName: 'Bun Build'
