trigger:
  - releases/*

pr: none

variables:
  system.debug: true
  CONTAINER_REGISTRY: acr
  REPOSITORY: yama-ui

stages:
- stage: Build
  jobs:
  - job: ContinuousIntegration
    pool:
      name: local
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'
    #
    # - script: |
    #     npm install -g bun
    #     bun install
    #     bunx --bun vite build # Build without verify with TypeScript
    #   displayName: 'Install Dependencies and Build Project'

    - bash: |
        ls -l
        pwd
        echo "$(System.DefaultWorkingDirectory)"
        echo "$(System.ArtifactsDirectory)"
        echo "$(Build.SourceBranch)"
        echo "$(Build.SourceBranchName)"
      displayName: Debug Info

    - script: env
      displayName: Environment variables

    - task: Docker@2
      inputs:
        command: buildAndPush
        containerRegistry: $(CONTAINER_REGISTRY)
        repository: $(REPOSITORY)
        dockerfile: 'Dockerfile'
        tags: |
          $(Build.SourceBranchName)
      displayName: Build and Push

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        archiveType: tar
        tarCompression: bz2
        includeRootFolder: false
        verbose: true

    # - task: PublishPipelineArtifact@0
    #   inputs:
    #     targetPath: '$(System.ArtifactsDirectory)'
    #     artifactName: drop
    #   displayName: "Publish Dockerfile"
